### ISSUE TITLE
CAPTCHA for fee replacement

### ISSUE THREAD

**Issue by padenmoss** [primecoin/rfcs#1]
Burning fees secures the blockchain by increasing costs for each transaction: In order to offset this fee, a CAPTCHA to send or receive would partially replace burned fees to prevent abuse.

**Comment by padenmoss** [comment]
After further pondering my previous comment and RFC-0002, I believe that the reputation of Primecoin will not be affected negatively, as the decision to burn XPM for every transaction will serve to protect the protocol.

To put RFC-0002 into perspective, there are currently around 4,500,000 primecoins added to the network every year, which equates to 375,000 per month; 86,539 per week; and 12,329 per day. Currently all transaction fees are also passed back to the miners, as well as the reward for discovering new prime-chains, which are infinite. Burning 1 XPM for every transaction would require over 12,000 transactions per day to balance inflation. However, without burning the transaction fee, recording 12,000 transactions at 250 bytes per transaction would increase the blockchain by around 2.8MB per day, or around 1GB per year!

One of the biggest problems with blockchain is chain bloat. Every transaction that occurs must be recorded--forever. This leads to extremely large blockchains that can make managing a node impossible for individual users. 

Take Ethereum--with their 300GB+ blockchain--as an example: There is no way for an individual user to maintain a "full node" with all the token contracts and transactions that must be recorded to maintain the EVM. According to the Bitcoin whitepaper [https://bitcoin.org/bitcoin.pdf], Satoshi intended users to operate a node on the network with the complete blockchain history, each mining SHA256 via CPU to reach consensus. In direct contradiction to the original vision of cryptocurrency, Ethereum has created light clients and introduced RPC nodes so users do not have to download the entire blockchain in order to access their assets. 

Primecoin's blockchain is currently only 4GB as of Q3 2020 and will continue to grow. This may create problems in the future unless there is some deterrent to ensure that unnecessary transactions do not occur or are performed off-chain. Burning the transaction fee will allow network participants to maintain the standard of a peer-to-peer electronic cash system while preventing blockchain obesity.

There is a cost to increasing the size of the blockchain that has not been accounted for within the original protocol. If the ledger becomes too large to download then new adopters will be excluded. This oversight is addressed in RFC-0002 after 7 years of experience within the blockchain ecosystem and we would be wise to support this correction.

Yes, implementing compacting proofs and light clients is possible, yet this creates dependency on prover and verifier nodes, which fragments the egalitarian ideals of a blockchain network.

I no longer believe burning primecoins could be an attack vector and community-governance would inevitably introduce corruption.
I'm closing this issue in support of RFC-0002.

**Comment by padenmoss** [comment]
Rather than destroy primecoins in fees I would prefer transaction witnesses are revealed by paying.

**Comment by padenmoss** [comment]
![INPRIMECOINWETRUSTLIBERTY_logo](https://github.com/user-attachments/assets/d0618c18-9cf1-45b6-86d8-f3c400d31212)

**Comment by sunnyking** [comment]
capcha is a centralized web service. i don't think it can replace fee which is part of decentralized protocol of blockchain
